name: sciborg_dev
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - comm=0.2.1=py311h06a4308_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ipykernel=6.29.5=py311h06a4308_0
  - ipython=8.27.0=py311h06a4308_0
  - jedi=0.19.1=py311h06a4308_0
  - jupyter_client=8.6.0=py311h06a4308_0
  - jupyter_core=5.7.2=py311h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - openssl=3.0.15=h5eee18b_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=24.2=py311h06a4308_0
  - platformdirs=3.10.0=py311h06a4308_0
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py311h06a4308_1
  - python=3.11.10=he870216_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - pyzmq=25.1.2=py311h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py311h5eee18b_0
  - traitlets=5.14.3=py311h06a4308_0
  - typing_extensions=4.11.0=py311h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.44.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.7
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - attrs==24.2.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - frozenlist==1.5.0
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.27.2
      - httpx-sse==0.4.0
      - idna==3.10
      - jiter==0.8.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.3.8
      - langchain-community==0.3.8
      - langchain-core==0.3.21
      - langchain-openai==0.2.10
      - langchain-text-splitters==0.3.2
      - langsmith==0.1.146
      - marshmallow==3.23.1
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - numpy==1.26.4
      - openai==1.55.1
      - orjson==3.10.12
      - packaging==24.2
      - propcache==0.2.0
      - pydantic==2.10.2
      - pydantic-core==2.27.1
      - pydantic-settings==2.6.1
      - python-dotenv==1.0.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.35
      - tenacity==9.0.0
      - tiktoken==0.8.0
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - urllib3==2.2.3
      - yarl==1.18.0
prefix: /home/parikh92/.conda/envs/cent7/2024.02-py311/sciborg_dev
