name: sciborg_beta
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.11.26=h06a4308_0
  - comm=0.2.1=py311h06a4308_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - faiss-cpu=1.9.0=py3.11_hadc1362_0_cpu
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=py311h06a4308_0
  - ipython=8.27.0=py311h06a4308_0
  - jedi=0.19.1=py311h06a4308_0
  - jupyter_client=8.6.0=py311h06a4308_0
  - jupyter_core=5.7.2=py311h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libfaiss=1.9.0=hf65b397_0_cpu
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - openssl=3.0.15=h5eee18b_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=24.2=py311h06a4308_0
  - platformdirs=3.10.0=py311h06a4308_0
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py311h06a4308_1
  - python=3.11.10=he870216_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - pyzmq=25.1.2=py311h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py311h5eee18b_0
  - traitlets=5.14.3=py311h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.44.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.7
      - aiosignal==1.3.1
      - aiosqlite==0.20.0
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - dataclasses-json==0.6.7
      - defusedxml==0.7.1
      - distro==1.9.0
      - duckduckgo-search==6.4.1
      - dydantic==0.0.7
      - fastjsonschema==2.21.1
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.27.2
      - httpx-sse==0.4.0
      - idna==3.10
      - isoduration==20.11.0
      - jinja2==3.1.4
      - jiter==0.8.0
      - json5==0.10.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - langchain==0.3.8
      - langchain-community==0.3.8
      - langchain-core==0.3.25
      - langchain-openai==0.2.10
      - langchain-text-splitters==0.3.2
      - langgraph==0.2.59
      - langgraph-checkpoint==2.0.9
      - langgraph-checkpoint-sqlite==2.0.1
      - langgraph-cli==0.1.65
      - langgraph-sdk==0.1.45
      - langsmith==0.1.146
      - markupsafe==3.0.2
      - marshmallow==3.23.1
      - mistune==3.0.2
      - msgpack==1.1.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - nbclient==0.10.2
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - notebook==7.3.1
      - notebook-shim==0.2.4
      - openai==1.55.1
      - orjson==3.10.12
      - overrides==7.7.0
      - packaging==24.2
      - pandocfilters==1.5.1
      - primp==0.8.3
      - prometheus-client==0.21.1
      - propcache==0.2.0
      - pycparser==2.22
      - pydantic==2.10.2
      - pydantic-core==2.27.1
      - pydantic-settings==2.6.1
      - python-dotenv==1.0.1
      - python-json-logger==3.2.1
      - pyyaml==6.0.2
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.22.3
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.35
      - tavily-python==0.5.0
      - tenacity==9.0.0
      - terminado==0.18.1
      - tiktoken==0.8.0
      - tinycss2==1.4.0
      - tqdm==4.67.1
      - trustcall==0.0.26
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - uri-template==1.3.0
      - urllib3==2.2.3
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - wikipedia==1.4.0
      - yarl==1.18.0
prefix: /home/parikh92/.conda/envs/cent7/2024.02-py311/sciborg_beta
